/**
 * Alias y siglas populares de universidades, para que el buscador entienda
 * "MIT", "UCLA", "Caltech" o "Georgia Tech".
 *
 * Están aparte y no dentro de universidades_seleccionadas6.json porque ese archivo
 * se regenera desde el Colab: los alias se perderían en cada exportación.
 *
 * La clave es el INSTNM EXACTO tal como viene en el JSON. Si el Colab cambia un
 * nombre, el alias simplemente deja de aplicarse (no rompe nada).
 *
 * No hace falta repetir siglas que se forman solas con las iniciales del nombre
 * (NYU, USC, UCLA, MIT...): el buscador ya las genera. Igual se dejan algunas
 * aquí por claridad cuando son muy conocidas.
 */
export const ALIASES: Record<string, string[]> = {
  // Ivy League y privadas muy conocidas
  'Harvard University': ['Harvard'],
  'Yale University': ['Yale'],
  'Princeton University': ['Princeton'],
  'Columbia University in the City of New York': ['Columbia', 'Columbia University', 'CU'],
  'Cornell University': ['Cornell'],
  'Brown University': ['Brown'],
  'Dartmouth College': ['Dartmouth'],
  'University of Pennsylvania': ['UPenn', 'Penn', 'Wharton'],
  'Massachusetts Institute of Technology': ['MIT'],
  'Stanford University': ['Stanford'],
  'California Institute of Technology': ['Caltech', 'Cal Tech'],
  'Duke University': ['Duke'],
  'Johns Hopkins University': ['JHU', 'Johns Hopkins', 'Hopkins'],
  'University of Chicago': ['UChicago', 'U Chicago'],
  'Northwestern University': ['Northwestern', 'NU'],
  'Carnegie Mellon University': ['CMU', 'Carnegie Mellon'],
  'Rice University': ['Rice'],
  'Vanderbilt University': ['Vandy', 'Vanderbilt'],
  'Washington University in St Louis': ['WashU', 'WUSTL'],
  'University of Notre Dame': ['Notre Dame', 'ND'],
  'Georgetown University': ['Georgetown'],
  'Emory University': ['Emory'],
  'Tufts University': ['Tufts'],
  'Boston University': ['BU'],
  'Boston College': ['BC'],
  'New York University': ['NYU'],
  'University of Southern California': ['USC'],
  'Case Western Reserve University': ['CWRU', 'Case Western'],
  'Rensselaer Polytechnic Institute': ['RPI', 'Rensselaer'],
  'Worcester Polytechnic Institute': ['WPI'],
  'Rochester Institute of Technology': ['RIT'],
  'Stevens Institute of Technology': ['Stevens'],
  'Illinois Institute of Technology': ['IIT', 'Illinois Tech'],
  'Florida Institute of Technology': ['FIT', 'Florida Tech'],
  'George Washington University': ['GWU', 'GW'],
  'Southern Methodist University': ['SMU'],
  'Texas Christian University': ['TCU'],
  'Brigham Young University': ['BYU'],
  'Loyola Marymount University': ['LMU'],
  'Tulane University of Louisiana': ['Tulane'],
  'Wake Forest University': ['Wake Forest', 'WFU'],
  'Syracuse University': ['Syracuse', 'Cuse'],
  'The Juilliard School': ['Juilliard'],
  'Harvey Mudd College': ['Mudd', 'HMC'],
  'Claremont McKenna College': ['CMC'],
  'William & Mary': ['William and Mary', 'W&M', 'College of William and Mary'],
  'Washington and Lee University': ['W&L', 'WLU'],

  // University of California
  'University of California-Berkeley': ['UC Berkeley', 'UCB', 'Berkeley', 'Cal'],
  'University of California-Los Angeles': ['UCLA'],
  'University of California-San Diego': ['UCSD', 'UC San Diego'],
  'University of California-Davis': ['UC Davis', 'UCD'],
  'University of California-Irvine': ['UC Irvine', 'UCI'],
  'University of California-Santa Barbara': ['UCSB', 'UC Santa Barbara'],
  'University of California-Santa Cruz': ['UCSC', 'UC Santa Cruz'],
  'University of California-Riverside': ['UCR', 'UC Riverside'],
  'University of California-Merced': ['UC Merced'],
  'University of California-San Francisco': ['UCSF'],

  // Otras de California
  'California Polytechnic State University-San Luis Obispo': ['Cal Poly', 'Cal Poly SLO'],
  'California State Polytechnic University-Pomona': ['Cal Poly Pomona', 'CPP'],
  'San Diego State University': ['SDSU'],
  'San Jose State University': ['SJSU'],

  // Públicas grandes
  'University of Michigan-Ann Arbor': ['UMich', 'Michigan', 'U of M'],
  'University of Virginia-Main Campus': ['UVA', 'UVa'],
  'University of North Carolina at Chapel Hill': ['UNC', 'UNC Chapel Hill'],
  'North Carolina State University at Raleigh': ['NC State', 'NCSU'],
  'Georgia Institute of Technology-Main Campus': ['Georgia Tech', 'GT', 'GaTech'],
  'University of Georgia': ['UGA'],
  'The University of Texas at Austin': ['UT Austin', 'UT', 'Texas'],
  'The University of Texas at Dallas': ['UTD', 'UT Dallas'],
  'The University of Texas at El Paso': ['UTEP'],
  'The University of Texas at San Antonio': ['UTSA'],
  'The University of Texas at Arlington': ['UTA', 'UT Arlington'],
  'Texas A&M University-College Station': ['Texas A&M', 'TAMU', 'A&M'],
  'University of Illinois Urbana-Champaign': ['UIUC', 'Illinois'],
  'University of Illinois Chicago': ['UIC'],
  'University of Wisconsin-Madison': ['UW Madison', 'Wisconsin'],
  'University of Washington-Seattle Campus': ['UW', 'UDub', 'University of Washington'],
  'University of Minnesota-Twin Cities': ['UMN', 'Minnesota'],
  'University of Maryland-College Park': ['UMD', 'Maryland'],
  'University of Maryland-Baltimore County': ['UMBC'],
  'Purdue University-Main Campus': ['Purdue'],
  'Indiana University-Bloomington': ['IU', 'Indiana'],
  'Ohio State University-Main Campus': ['OSU', 'Ohio State', 'tOSU'],
  'Pennsylvania State University-Main Campus': ['Penn State', 'PSU'],
  'Michigan State University': ['MSU'],
  'University of Florida': ['UF'],
  'Florida State University': ['FSU'],
  'University of Central Florida': ['UCF'],
  'University of South Florida': ['USF'],
  'Florida International University': ['FIU'],
  'University of Miami': ['UM', 'The U'],
  'Arizona State University Campus Immersion': ['ASU', 'Arizona State'],
  'University of Arizona': ['UA', 'UofA', 'Arizona'],
  'University of Colorado Boulder': ['CU Boulder', 'Colorado'],
  'Colorado School of Mines': ['Mines'],
  'University of Utah': ['Utah', 'UofU'],
  'Oregon State University': ['OSU Oregon'],
  'University of Oregon': ['UO', 'Oregon'],
  'Rutgers University-New Brunswick': ['Rutgers', 'RU'],
  'University of Massachusetts-Amherst': ['UMass', 'UMass Amherst'],
  'University of Connecticut': ['UConn'],
  'University of Pittsburgh-Pittsburgh Campus': ['Pitt', 'UPitt'],
  'Virginia Polytechnic Institute and State University': ['Virginia Tech', 'VT'],
  'Virginia Commonwealth University': ['VCU'],
  'Louisiana State University and Agricultural & Mechanical College': ['LSU'],
  'University of Nevada-Las Vegas': ['UNLV'],
  'University of Nevada-Reno': ['UNR'],
  'University of Iowa': ['UIowa'],
  'Iowa State University': ['ISU'],
  'University of Missouri-Columbia': ['Mizzou'],
  'Missouri University of Science and Technology': ['Missouri S&T'],
  'University of Kansas': ['KU'],
  'University of Kentucky': ['UK'],
  'University of Nebraska-Lincoln': ['UNL'],
  'The University of Alabama': ['Alabama', 'Bama'],
  'University of Alabama at Birmingham': ['UAB'],
  'University of Houston': ['UH'],
  'University of New Mexico-Main Campus': ['UNM'],
  'Stony Brook University': ['SBU', 'SUNY Stony Brook'],
  'University at Buffalo': ['UB', 'SUNY Buffalo'],
  'Binghamton University': ['SUNY Binghamton'],
  'University at Albany': ['SUNY Albany'],

  // CUNY
  'CUNY Bernard M Baruch College': ['Baruch'],
  'CUNY Hunter College': ['Hunter'],

  // Academias militares
  'United States Military Academy': ['West Point', 'USMA', 'Army'],
  'United States Naval Academy': ['USNA', 'Navy', 'Annapolis'],
  'United States Air Force Academy': ['USAFA', 'Air Force'],
  'United States Coast Guard Academy': ['USCGA', 'Coast Guard'],
};
